### ISSUE TITLE
Use of RFC 5646 Language codes

### ISSUE THREAD

**Issue by kevinburrows** [AMWA-TV/AS-11_Overview#11]
For consistency, should the use of the language codes be limited to the 2 letter 'language tag' only, 
or allow a mixed economy with "language tag" and "region sub-tag" combined
e.g. fin = fi-SE = finnish-SWEDEN.

**Comment by mglanville** [comment]
Our intention was that implementations should fully support [IETF RFC 5646](https://tools.ietf.org/html/rfc5646), which is considered [Best Current Practice](https://tools.ietf.org/html/bcp47).

Some key points:
* When creating a file, it is possible to enter any valid language tag
* When reading a file, it is possible to extract as much or as little information from the language tag as is required for the application

The choice of language tag is best governed by the [rules](https://tools.ietf.org/html/bcp47#section-4)  set out in RFC 5646.

The advantages of using RFC 5646, rather than writing our own set of constraints on top of ISO 693-2, ISO 693-3 or an arbitrary list of languages include:
* all of the rules for how best to choose a language tag are already set out
* there are software libraries available so implementers don't have to start from scratch
* some linguistics and computer science experts have done all the work for us and solved the problem; every language the global broadcast industry is going to want to describe is covered and we didn't even have to think about it
    + _if something is not yet covered then there is a process for adding it, and by doing so we help the whole world, not just our own little community_

**Comment by kevinburrows** [comment]
OK that seems a good approach, we'll need to draw up some guidance for its use in the broadcaster guidelines.
