### ISSUE TITLE
Make AS-11 GitHub pages consistent with NMOS

### ISSUE THREAD

**Issue by peterbrightwell** [AMWA-TV/AS-11_Overview#129]
https://amwa-tv.github.io/nmos* pages have headers and menus. It would be quite easy to add these to AS-11 pages also (add Gemfile, _config.yml, _layouts/default.html and assets/*)

**Comment by peterbrightwell** [comment]
For an example of what it might look like see https://peterbrightwell.github.io/AS-11_X1/

The only required change to existing pages is to add a couple of lines of "front matter" to tell Jekyll about the required layout.

**Comment by matthewmarks-bbc** [comment]
There are some issues with this when it comes to the web page renderings ([https://peterbrightwell.github.io/AS-11_X1/AMWA_AS_11_X1.html](https://peterbrightwell.github.io/AS-11_X1/AMWA_AS_11_X1.html)).

* The trapped menu bar will obscure an element which is referenced by a fragment at the end of the URL, because that will scroll to the top of the screen
* The formatting has been affected, and the page is skewed horizontally relative to the banner

**Comment by peterbrightwell** [comment]
The fragment obscuring issue is was fixed for NMOS in https://github.com/AMWA-TV/nmos-doc-layouts/issues/2.
Spacing still needs fixing (https://github.com/AMWA-TV/nmos-doc-layouts/issues/3)

**Comment by thomasheritage** [comment]
We understand that the rendering of the NMOS specs is going to be looked at again anyway. After that, and if implementing the changes doesn't affect the operation or appearance of the AS-11 Specs then this could be revisited, if required.
For now, as part of tidying up AS-11 issues and only addressing essential matters, I'll close this issue.
