### ISSUE TITLE
Tidy releases of all AS-11 Specs

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#136]
- [x] For all AS-11 Specs, revert release titles (so that the Specification level terms used match those in the Specification included in the bundled release)
- [ ] For all AS-11 Specs, create a new release (+ 0.0.1) if the Specification level terms used in the previous release are out-of-date. Include a small changelog of major changes (probably not much except these Specification level changes, but check)

**Comment by thomasheritage** [comment]
DO this after other issues e.g. #137

**Comment by Matthew-Marks** [comment]
Specs that need point releases due to having latest release before 20180718 when the Spec Level terms were changed:

- [x] UK_DPP_SD (`Specification` -> `Specification (Stable)`)
- [x] UK_DPP_HD (`Specification` -> `Specification (Stable)`)
- [x] X2 (`Proposed Specification` -> `Specification`)
- [x] X7 (`Proposed Specification` -> `Specification`)
- [x] X9 (`Proposed Specification` -> `Specification`)
