### ISSUE TITLE
AS-11 X2 change from WIP to Proposed Specification

### ISSUE THREAD

**Issue by kevinburrows** [AMWA-TV/AS-11_Overview#53]
Change of text on header of specification pages from 'Work in Progress' to 'Proposed Specification', and include a note that the specification IDs will be updated by the end of July.

**Comment by thomasheritage** [comment]
I think all that we can do for now is to add a note explaining that this Specification has been approved for elevation to "Proposed Specification". It should still be classified as "WIP" for now because to take the next maturity step the following is necessary:
* All Rules Framework Components need new, permanent, IDs
* The values used in the Specification_Identifiers Element need to be updated

It would be very misleading to title the Specification "Proposed Specification" if it still contains WIP content.

**Comment by kevinburrows** [comment]
We agreed on our call on Wednesday that we would change X2 to proposed specification status with a note explaining that the IDs need to be updated, as you had no time available to do this before the end of July.
We should go ahead on this basis, or find another way to carry out the updates much earlier. (e.g. something I could do or help with)

I suggest we discuss later

**Comment by thomasheritage** [comment]
We will discuss then on the call on Wednesday

**Comment by thomasheritage** [comment]
1. Add a note to the top of the README and the top of the HTML rendering (link into "WIP" status using "*") stating that the Spec is approved for elevation to Proposed and the relevant changes will be made by the end of July 2016.
2. Update Specification_Identifiers values and change status from "WIP" to "Proposed Specification"
3. Change Rules Framework Component IDs

**Comment by thomasheritage** [comment]
Steps 3) and 2) are not actually quite so independent -- the ID of each Block containing an XML Schema is used as the Namespace for the Schema. Therefore, the change in Rules Framework Component IDs _does_ have a substantive effect on the Specification. So, step 3) above actually needs to be performed before Step 2) can be completed.

**Comment by thomasheritage** [comment]
When the elevation is complete we will need to make new sample MXF files.

**Comment by thomasheritage** [comment]
The notes about the status of AS-11 X2 have now been added to the Spec.

**Comment by thomasheritage** [comment]
Changes made. v1.0.0 released at https://github.com/AMWA-TV/AS-11_X2/releases

Sample files refresh covered by #63
