### ISSUE TITLE
Enable write access permission for Github X2, X3 and X4 repositories

### ISSUE THREAD

**Issue by kevinburrows** [AMWA-TV/AS-11_Overview#54]
To enable @kevinburrows to edit wiki pages for X2, X3 and X4

**Comment by bgilmer77** [comment]
Done

________________________________

**Comment by thomasheritage** [comment]
There has never been any wiki content for any of the individual AS-11 Specifications -- https://github.com/AMWA-TV/AS-11_Overview is used for both Wiki and Issues for all AS-11 Specifications. I have just been through the repository settings and made sure that Wiki and Issues are disabled for all AS-11 repositories to avoid confusion (I thought I'd done that previously but I found that actually the Wiki was enabled for several repositories). If we now need to take a different approach for some reason then that's something we should discuss -- let me know.

I wonder if perhaps @kevinburrows was referring to the files ("Code") inside the Specification repositories rather than the Wikis? Each GitHub Specification repository is generated from the Rules Framework Components (and other resources) using a set of tools. Therefore, files in these repositories must not be directly edited (indeed, if they were edited then any changes would simply be overwritten / reverted the next time that the Specification repository was re-generated).

**Comment by kevinburrows** [comment]
I was referring to the README and other text files at this stage rather than the code files.

**Comment by thomasheritage** [comment]
OK thanks for clarifying. Note that *all* files in the Specification repository are managed / generated by automated tools therefore no files at all in a Specification GitHub repository can be directly edited.
