### ISSUE TITLE
Both AS-11 X3 and AS-11 X4 should support HDR

### ISSUE THREAD

**Issue by thomasheritage** [AMWA-TV/AS-11_Overview#9]
This means that:
* the Transfer Characteristic does not have to be as defined in 709
* the additional MXF & AVC "video fundamentals" signalling included in AS-11 X1 should probably also be added to AS-11 X3 and AS-11 X4

**Comment by mglanville** [comment]
@thomasheritage Regarding the "video fundamentals" signalling, I doubt we want _exactly_ the same constraints as AS-11 X1.

The MXF-layer constraints include a requirement that "Signal Standard" (in the Essence Descriptor) is not present or has a value of 0.

I don't think we want that because (unlike for the UHD Essence in AS-11 X1) there will be legitimate, correct values that can describe the content in AS-11 X3 and AS-11 X4.

The AVC-layer "video fundamentals" signalling constraints from AS-11 X1 are suitable for reuse in AS-11 X3 and AS-11 X4.

**Comment by thomasheritage** [comment]
This needs further further review before implementation

**Comment by thomasheritage** [comment]
Agreed that for the time being X3 and X4 will not support HDR
